### ISSUE TITLE
"no module named 'sqflint'"

### ISSUE THREAD

**Issue by Fusselwurm** [LordGolias/linter-sqf#2]
I may be just too stupid for python on Windows, buuuut here goes: 

* installed python to `c:\python34`
* installed sqflint to `c:\python34\scripts` using pip
* installed sqflint package in atom
* set "Executable Path" in package options to `c:\python34\Scripts\sqflint.exe`
* When opening/saving sqf files, the following error is thrown in Atom:

```
linter-registry.js:137 [Linter] Error running SQFlint Error: Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python34\Scripts\sqflint.exe\__main__.py", line 5, in <module>
ImportError: No module named 'sqflint'
    at ChildProcess.<anonymous> (C:\Users\fusselwurm\.atom\packages\linter-sqf\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

note:
*  `c:\python34\scripts\sqflint.py` AND `c:\python34\scripts\sqflint.exe` DO exist

Any ideas?

**Comment by Fusselwurm** [comment]
nvm. :disappointed_relieved: 

I played around with python paths for a bit, then restarted Windows… now it works. ¯\\_(ツ)_/¯

**Comment by Drofseh** [comment]
I am also getting this error. Restarting does not help.

Paths are
`C:\Users\Username\AppData\Local\Programs\Python\Python37-32`
`C:\Users\Username\AppData\Local\Programs\Python\Python37-32\Scripts\sqflint.exe`


![](https://i.gyazo.com/98001d9fb6b8cc142c5f8d725c7eabf0.png)

**Comment by EM-Creations** [comment]
Make sure your `PYTHONPATH` environment variable is set to your Python Scripts directory.
