### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iDanny1212** [LordGolias/linter-sqf#4]
```
[Linter] Error running SQFlint Error: Traceback (most recent call last):
  File "c:\users\danny\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\danny\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\Scripts\sqflint.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'sqflint'
    at ChildProcess.<anonymous> (C:\Users\danny\.atom\packages\linter-sqf\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

I'm getting this error while opening a sqf file, can someone help me?

**Comment by rlnt** [comment]
ModuleNotFoundError: No module named 'sqflint'

You probably failed the installation. Make sure you did all steps. Installing the package from the atom package browser isn't enough. You also need to download the repository, run the command prompt from the extracted folder and run the installer with python's pip.

**Comment by EM-Creations** [comment]
Make sure your `PYTHONPATH` environment variable is set to your Python Scripts directory.
